package examples.mysql.connector.packet.connection;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;

import examples.mysql.connector.datatypes.le.LEInteger;
import examples.mysql.connector.datatypes.string.LengthEncodedString;
import examples.mysql.connector.packet.CapabilityFlags;
import io.github.zhtmf.DataPacket;
import io.github.zhtmf.annotations.modifiers.Conditional;
import io.github.zhtmf.annotations.modifiers.EndsWith;
import io.github.zhtmf.annotations.modifiers.Length;
import io.github.zhtmf.annotations.modifiers.ListLength;
import io.github.zhtmf.annotations.modifiers.LittleEndian;
import io.github.zhtmf.annotations.modifiers.Order;
import io.github.zhtmf.annotations.modifiers.Signed;
import io.github.zhtmf.annotations.modifiers.Unsigned;
import io.github.zhtmf.annotations.types.BYTE;
import io.github.zhtmf.annotations.types.CHAR;
import io.github.zhtmf.annotations.types.INT;
import io.github.zhtmf.annotations.types.RAW;
import io.github.zhtmf.converters.auxiliary.DataType;
import io.github.zhtmf.converters.auxiliary.ModifierHandler;

@Unsigned
@LittleEndian
public class HandshakeResponse41 extends DataPacket{

    @Order(0)
    @INT
    @Signed
    //Capabilities Flags, CLIENT_PROTOCOL_41 always set.
    public long clientFlag;
    
    @Order(1)
    @INT
    public long maxPacketSize;
    
    @Order(2)
    @BYTE
    //  client charset a_protocol_character_set, only the lower 8-bits
    public int charSet;
    
    @Order(3)
    @RAW(23)
    //filler to the size of the handhshake response packet. All 0s.
    public byte[] filler = new byte[23];
    
    @Order(4)
    @CHAR
    @EndsWith({'\0'})
    public String username;
    
    /*
     * opaque authentication response data generated by 
     * Authentication Method indicated by the plugin name field.
     */
    @Order(5)
    @Conditional(Conditionals.class)
    public LengthEncodedString authResponse;
    @Order(6)
    @CHAR
    @Length(type=DataType.BYTE)
    @Conditional(value=Conditionals.class,negative=true)
    public String authResponseWithLength;
    
    @Order(7)
    @CHAR
    @EndsWith({'\0'})
    @Conditional(Conditionals.class)
    public String database;
    
    @Order(8)
    @CHAR
    @EndsWith({'\0'})
    @Conditional(Conditionals.class)
    public String clientPluginName;
    
    @Order(9)
    @Conditional(Conditionals.class)
    public ClientConnectAttrs attrs;
    
    public static class ClientConnectAttrs extends DataPacket{
        @Order(0)
        public LEInteger lengthAllkeyValues;
        @Order(1)
        @ListLength(handler=LengthHandler.class)
        public List<KeyValue> keyValue;
        
        public static class LengthHandler extends ModifierHandler<Integer>{

            @Override
            public Integer handleDeserialize0(String fieldName, Object entity, InputStream is) throws IOException {
                return ((ClientConnectAttrs)entity).lengthAllkeyValues.getNumericValue().intValue();
            }

            @Override
            public Integer handleSerialize0(String fieldName, Object entity) {
                return ((ClientConnectAttrs)entity).lengthAllkeyValues.getNumericValue().intValue();
            }
        }
    }
    
    public static class KeyValue extends DataPacket{
        @Order(0)
        public LengthEncodedString key;
        @Order(1)
        public LengthEncodedString value;
        
        public KeyValue() {
        }
        public KeyValue(String k, String v) {
            this.key = new LengthEncodedString(k);
            this.value = new LengthEncodedString(v);
        }
    }
    
    public static class Conditionals extends ModifierHandler<Boolean>{
        @Override
        public Boolean handleDeserialize0(String fieldName, Object entity, InputStream is) throws IOException {
            HandshakeResponse41 resp = (HandshakeResponse41)entity;
            switch(fieldName) {
            case "authResponse":
            case "authResponseWithLength":
                return (resp.clientFlag & CapabilityFlags.CLIENT_PLUGIN_AUTH_LENENC_CLIENT_DATA) != 0;
            case "database":
                return (resp.clientFlag & CapabilityFlags.CLIENT_CONNECT_WITH_DB) != 0;
            case "clientPluginName":
                return (resp.clientFlag & CapabilityFlags.CLIENT_PLUGIN_AUTH) != 0;
            case "attrs":
                return (resp.clientFlag & CapabilityFlags.CLIENT_CONNECT_ATTRS) != 0;
            }
            throw new IllegalArgumentException(fieldName);
        }
        @Override
        public Boolean handleSerialize0(String fieldName, Object entity) {
            HandshakeResponse41 resp = (HandshakeResponse41)entity;
            switch(fieldName) {
            case "authResponse":
            case "authResponseWithLength":
                return (resp.clientFlag & CapabilityFlags.CLIENT_PLUGIN_AUTH_LENENC_CLIENT_DATA) != 0;
            case "database":
                return (resp.clientFlag & CapabilityFlags.CLIENT_CONNECT_WITH_DB) != 0;
            case "clientPluginName":
                return (resp.clientFlag & CapabilityFlags.CLIENT_PLUGIN_AUTH) != 0;
            case "attrs":
                return (resp.clientFlag & CapabilityFlags.CLIENT_CONNECT_ATTRS) != 0;
            }
            throw new IllegalArgumentException(fieldName);
        }
    }
}